language: python

python:
  - 3.2

before_script:
  - liquidluck server -d -s ~/.liquidluck-themes/arale2/settings.yml
  - sleep 5

install: 
  - pip install liquidluck
  - liquidluck install alipay/arale2 -g
  - curl -O https://raw.github.com/jcarver989/phantom-jasmine/master/lib/run_jasmine_test.coffee
  - npm install phantomjs -g
  
script: phantomjs run_jasmine_test.coffee http://127.0.0.1:8000/tests/runner.html