language: node_js

node_js:
  - 0.6
  - 0.8

before_script:
  - git clone https://github.com/alipay/liquidluck-theme-arale2.git ../liquidluck-theme-arale2
  - cp -r ../liquidluck-theme-arale2/* tests/
  - nohup node tests/test-travis.js &

install: 
  - npm install spm node-static swig
  - spm install
  
script: phantomjs run_jasmine_test.coffee http://127.0.0.1:8000/tests/runner.html

env:
  global:
    - TIMEOUT=500