language: python

node_js:
  - 3.2

before_script:
  - @nohup make server &

install: 
  - pip install liquidluck
  - liquidluck install alipay/arale2 -g
  - curl -O https://raw.github.com/jcarver989/phantom-jasmine/master/lib/run_jasmine_test.coffee
  - npm install phantomjs -g